### ISSUE TITLE
program not opening

### ISSUE THREAD

**Issue by Real-FloridaMan** [hakolao/sandbox#10]
i extract the file and run the executable and it creates a text file called engine_run.log which contains the text, "20:13:04 [INFO] Creating renderer for window size [1920, 1080]" and then nothing else happens. I am on windows and i have python, cmake, and ninja installed, and i have allowed the program to run. Any ideas?

**Comment by hakolao** [comment]
I hadn't ran this in a long time, but just did on my new windows laptop without issues. 

I tried both the release executable and compiled from scratch. So, hard to say what could be wrong.

What gpu do you have? The next step in the logs would be 

```
19:03:11 [INFO] Using device NVIDIA GeForce RTX 3080...
```

So I'm assuming it fails before that, trying to use the device...

This project uses https://github.com/vulkano-rs/vulkano for the rendering side of things so one thing to try is if you can run their examples fine then this should work too.

**Comment by Real-FloridaMan** [comment]
thanks alot for your response, heres what i tried. after reading your response i kinda realized that this program seems to be a lot harder to run than i thought. I was originally trying to run it on a thinkpad laptop with intigrated graphics. I tried on my home computer, with signifigantly better specs, and the program did open, but it instantly froze and as soon as i tried to click anything it would stop responding. the GPU is an RX6400, and as for the cpu ill have to check, let me know if you need it.

**Comment by hakolao** [comment]
So, I've got another project that has run into this issue on AMD gpus. I am pretty sure it's still my bug, but haven't been able to figure it out because of not owning an amd device.

I pushed a potential change that could affect this, but hard to say.

You could try pulling the latest change and try `cargo run --release` again.

**Comment by Real-FloridaMan** [comment]
thanks again for the response. Im pretty new to guithub, so im not entirely sure what you mean. Could you elaborate further?

**Comment by hakolao** [comment]
That would require use of the command prompt. 

1. Install git for windows https://git-scm.com/book/en/v2/Getting-Started-Installing-Git
2. Open command prompt, type `git clone https://github.com/hakolao/sandbox` enter
3. type `cd sandbox` to enter the folder of the project
4. type `cargo run --release`. If you don't have Rust (and cargo) installed, install that first https://www.rust-lang.org/tools/install, reopen command prompt and try again (`cd sandbox`) then `cargo run --release`.

There may be some things missing from this, but running this indeed needs some technicality. Apologies. This isn't really a game, more of a test project to learn to make pixel simulations.
